name: "default-mario-aio"
author: "Your Name"
description: "Description of default-mario-aio."
category: "FPV"
sensor: ""  # Set sensor file if needed
files:
  wfb.yaml:
    wireless.txpower: "1"
    wireless.channel: "161"
  majestic.yaml:
    fpv.enabled: "false"
    system.logLevel: "debug"
