name: "default-mario-aio"
author: "ViperZ28"
description: "Description of default-mario-aio."
category: "FPV"
sensor: ""  # Set sensor file if needed
state: "Experimental"
files:
  wfb.yaml:
    wireless.txpower: "1"
    wireless.channel: "161"
  wfb.conf:
    txpower: "1"
    channel: "100"
  majestic.yaml:
    fpv.enabled: "false"
    system.logLevel: "debug"
