name: "high-power-fpv"
author: "OpenIPC Dev"
description: "Description of high-power-fpv."
category: "FPV"
sensor: ""  # Set sensor file if needed
status: "Experimental"
tags: [ "high-power", "fpv" ]
files:
  wfb.yaml:
    wireless.txpower: "20"
    wireless.channel: "173"
  majestic.yaml:
    fpv.enabled: "false"
    system.logLevel: "debug"
    video0.codec: "h264"
    video0.fps: "120"
